<?php
	require_once("../database_connection/dbconnection.php");
	$table='ajax_data';
	if(empty($_POST['a_id']))
	{
		$data=array(
			'name'=>$_POST['name'],
			'email'=>$_POST['email'],
			'password'=>$_POST['password'],
		);
		$res=$DB->insert($table,$data);	
	}
	else
	{
		$where['a_id']=$_POST['a_id'];
		$res=$DB->update($table,$_POST,$where);
	}
?>